version: '3.8'

services:
  db:
    image: postgres:15
    container_name: advertising-db
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - advertising-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: advertising-app
    restart: on-failure
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - advertising-net

volumes:
  db_data:

networks:
  advertising-net:
    driver: bridge
