version: '3.8'

services:
  db:
    image: postgres:15
    container_name: advertising-db
    restart: always
    env_file:
      - .env  # load DB credentials and name
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d:ro  # run .up.sql files on first startup
    networks:
      - advertising-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: advertising-app
    restart: on-failure
    depends_on:
      - db
    env_file:
      - .env  # load application settings (PORT, DB_HOST, etc.)
    ports:
      - "8080:8080"
    networks:
      - advertising-net

volumes:
  db_data:

networks:
  advertising-net:
    driver: bridge
